### ISSUE TITLE
Doesn't sort JSON that is invalid but still able to be parsed

### ISSUE THREAD

**Issue by GarrisonD** [Gudahtt/prettier-plugin-sort-json#57]
When a file is not pretty (e.g. there is a trailing `,`) then the first `npx prettier --write file.json` makes it pretty (removes the trailing `,`) and the second one sorts the keys using your plugin.

When the file is pretty, then everything works like a charm.

**Comment by GarrisonD** [comment]
Both `prettier` and prettier-plugin-sort-json` are the latest.

**Comment by Gudahtt** [comment]
Thanks for the report! This is a known limitation, and it only affects _invalid_ JSON. If there is a formatting issue (e.g. an indentation problem), the sorting works fine on the first pass. But there are some JSON validity issues that `prettier` will fix, like trailing commas, that cause `JSON.parse` to blow up.

We might be able to solve this by parsing the file more loosely, using some alternative to `JSON.parse`. Or maybe we can move the sorting into the parsing phase, rather than the preprocessing phase which is where it is now.

**Comment by Gudahtt** [comment]
I managed to fix this in #100 by rewriting the plugin to no longer use `JSON.parse`. This will be included in the next release.
